version: '3'
services:
  redis:
    image: redis:7.2.6-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

  mongodb:
    image: mongodb/mongodb-community-server:6.0.11-ubi9
    container_name: mongodb-container
    ports:
      - "27017:27017"
    restart: always

  mysql:
    image: mysql:lts
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  redis-data:
  mysql-data:
